services:
  postgres:
    image: postgres:16-alpine
    container_name: nutrition-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - env/development/docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
